### ISSUE TITLE
Adding dates would make this repository more awesome.

### ISSUE THREAD

**Issue by reddy6ue** [Elfocrash/awesome-cosmosdb#1]
In tech, it's always good to know when the utility of a particular link on the web diminishes and we should leave it to the user to decide. I suggest adding publish dates to every link included on this README.

Suggest also adding this to Contribution Guidelines.

**Comment by Elfocrash** [comment]
I would be happy to add this for blogs/articles and videos. 
It doesn’t seem that tools and documentation would need that.

**Comment by reddy6ue** [comment]
Agreed. Can update the pull request to reflect this. Although, even tools and documentation become obsolete with different versions.

**Comment by Elfocrash** [comment]
Even they become obsolete they stop being awesome and we will just remove them. I only wanna keep relevant stuff in the list.

**Comment by reddy6ue** [comment]
Makes sense.

**Comment by Elfocrash** [comment]
Feel free to go for the pull request.

**Comment by reddy6ue** [comment]
Also added that line in Contribution guidelines. Please accept pull request.

**Comment by reddy6ue** [comment]
I have another open pull request at the top of the page. This is the change to the Contribution guidelines.
